# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/flood_exercise',
                'doc_host': 'https://reutkeller.github.io',
                'git_url': 'https://github.com/reutkeller/flood_exercise',
                'lib_path': 'flood_exercise'},
  'syms': {'flood_exercise.core': {'flood_exercise.core.foo': ('core.html#foo', 'flood_exercise/core.py')}}}
