# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/flood_exercise',
                'doc_host': 'https://reutkeller.github.io',
                'git_url': 'https://github.com/reutkeller/flood_exercise',
                'lib_path': 'flood_exercise'},
  'syms': { 'flood_exercise.const_vals': {},
            'flood_exercise.core': {'flood_exercise.core.foo': ('core.html#foo', 'flood_exercise/core.py')},
            'flood_exercise.imgs_stats': { 'flood_exercise.imgs_stats.ImgsStatistics': ( 'statistics.html#imgsstatistics',
                                                                                         'flood_exercise/imgs_stats.py'),
                                           'flood_exercise.imgs_stats.ImgsStatistics.__init__': ( 'statistics.html#imgsstatistics.__init__',
                                                                                                  'flood_exercise/imgs_stats.py'),
                                           'flood_exercise.imgs_stats.ImgsStatistics._get_region_name_': ( 'statistics.html#imgsstatistics._get_region_name_',
                                                                                                           'flood_exercise/imgs_stats.py')},
            'flood_exercise.utils_func': { 'flood_exercise.utils_func.load_tif_paths': ( 'utilities.html#load_tif_paths',
                                                                                         'flood_exercise/utils_func.py')}}}
