# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/CONSTANTS.ipynb.

# %% auto 0
__all__ = ['GET_TIF_STR', 'SPLIT_TILES_NAMES_STR', 'REGION_STR', 'PATH_STR']

# %% ../nbs/CONSTANTS.ipynb 4
GET_TIF_STR = "*.tif"

SPLIT_TILES_NAMES_STR = '_'

REGION_STR ='region'
PATH_STR = 'path'
