# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/CONSTANTS.ipynb.

# %% auto 0
__all__ = ['GET_TIF_STR', 'SPLIT_TILES_NAMES_STR2', 'SPLIT_TILES_NAMES_STR1', 'REGION_STR', 'PATH_STR', 'STR_BAND_NAME',
           'STR_MEAN', 'STR_STD']

# %% ../nbs/CONSTANTS.ipynb 4
GET_TIF_STR = "*.tif"

SPLIT_TILES_NAMES_STR2 = '_'
SPLIT_TILES_NAMES_STR1 = "\\"

REGION_STR ='region'
PATH_STR = 'path'

STR_BAND_NAME = 'band'
STR_MEAN = 'mean'
STR_STD = 'std'
