# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/CONSTANTS.ipynb.

# %% auto 0
__all__ = ['GET_FILE_STR', 'SPLIT_TILES_NAMES_STR2', 'SPLIT_TILES_NAMES_STR1', 'REGION_STR', 'PATH_STR', 'JOIN_COL_NAME',
           'STR_BAND_NAME', 'STR_MEAN', 'STR_STD', 'DF_ID_COL_NAME', 'SPLIT_COL_NAME', 'GREEN_BAND', 'NIR_BAND',
           'IMG_PATH_WATER_STR', 'WATER_PERC_STR', 'REGION_STR_2']

# %% ../nbs/CONSTANTS.ipynb 4
# task 1 constants
GET_FILE_STR = "*.tif"

SPLIT_TILES_NAMES_STR2 = '_'
SPLIT_TILES_NAMES_STR1 = "\\"

REGION_STR ='region'
PATH_STR = 'path'
JOIN_COL_NAME = 'name_for_join'

STR_BAND_NAME = 'band'
STR_MEAN = 'mean'
STR_STD = 'std'

DF_ID_COL_NAME = 'id'
SPLIT_COL_NAME ='split'

# %% ../nbs/CONSTANTS.ipynb 5
# task 2 constants
GREEN_BAND =3
NIR_BAND = 8

# names for water percentage columns

IMG_PATH_WATER_STR = 'img_path'
WATER_PERC_STR = 'percentage_water'

# Region name to for tile filtering
REGION_STR_2 = 'Bolivia'

