# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/train_ml.ipynb.

# %% auto 0
__all__ = ['classification_pixels']

# %% ../nbs/train_ml.ipynb 4
import rasterio
import numpy as np
import pandas as pd
# import geopandas as gpd
# import matplotlib.pyplot as plt


from . import utils_func
from . import const_vals as CONST

# %% ../nbs/train_ml.ipynb 5
class classification_pixels():
  
  def __init__(self,
               path_labels_str : str , #path to the labeled images
               path_imgs_str : str , #path to S2 images to be used for train
               ):
    
    self.path_labels = utils_func.load_list_paths(path = path_labels_str , filter_file = True)
    self.path_imgs = utils_func.load_list_paths(path = path_imgs_str , filter_file= True)

    dfs_pixels = []
    for label_path in self.path_labels:
      id_path = label_path.split(CONST.SPLIT_TILES_NAMES_STR1)[-1].split(CONST.SPLIT_TILES_NAMES_STR2)[1]
      
      #find the matching S2 image
      s2_img_path = [x for x in self.path_imgs if id_path in x]
      
      if len(s2_img_path)==1:

        s2_img = rasterio.open(s2_img_path[0]).read()
        cols = rasterio.open(s2_img_path[0]).descriptions + rasterio.open(label_path).descriptions
        label_img = rasterio.open(label_path).read()
        

        # Stack the imags 
        stacked_img = np.concatenate((s2_img, label_img), axis=0)
        
        df_pixels = pd.DataFrame(stacked_img.reshape([stacked_img.shape[0],-1]).T)
        df_pixels.columns = cols
        dfs_pixels.append(df_pixels)

      else:
        continue

    self.df_res = pd.concat(dfs_pixels)

    
