# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/NDWI.ipynb.

# %% auto 0
__all__ = ['ndwi']

# %% ../nbs/NDWI.ipynb 3
import rasterio
import matplotlib.pyplot as plt 

from . import utils_func
from . import const_vals as CONST

# %% ../nbs/NDWI.ipynb 4
class ndwi():

  def __init__(self,
      path_to_imgs : str , # path to the folder that contains the images
      ):
     
     # get list of tif files
     self.list_of_files = utils_func.load_list_paths(path_to_imgs,filter_file = True)

     # calculate NDWI per image

     for path in self.list_of_file:
         self.ndwi_img = self._ndwi_s2_(path)
  
     #TODO : understand what should be the output - masked image ? 
         
  def _ndwi_s2_(self ,
                     path):
         
         with rasterio.open(path) as src:
            green = src.read(CONST.GREEN_BAND)
            nir = src.read(CONST.NIR_BAND)

            ndwi = (green - nir) / (green + nir)

         return ndwi
     



