# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05TFRecord.ipynb.

# %% auto 0
__all__ = ['ConvertTRF']

# %% ../nbs/05TFRecord.ipynb 4
import tensorflow as tf
import rasterio
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


from . import utils_func as util
from . import const_vals as CONST

# %% ../nbs/05TFRecord.ipynb 5
class ConvertTRF():


  def __init__(self,
    path_to_tif : str , #path to GeoTIFF files
    path_save_trf : str , # path to the folder that will store the result trf Records files
    ):

    self.list_of_tif = util.load_list_paths(path = path_to_tif , filter_file = False)



  def _convert_img_to_feature_(self, 
                               path_to_img : str , #path to specific image
                               ):
    with rasterio.open(path_to_img) as src:

      bands = src.descriptions
      arr = src.read()

      # convert to dataframe in order to convert later to feature #TODO - MAKE IT OWKRS WITH NUMPY ARRAY
      df = pd.DataFrame(arr.reshape([arr.shape[0],-1]).T)
      df.columns = bands
      

      
      

    






