# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utilities.ipynb.

# %% auto 0
__all__ = ['load_tif_paths']

# %% ../nbs/utilities.ipynb 3
import glob

from . import const_vals as CONST

# %% ../nbs/utilities.ipynb 4
def load_tif_paths(
    tif_path : str , # path to the folder where all the tifs are located
    )-> list :

    """
    Takes a folder path containing TIFF files and returns a list of paths
    that can be read by rasterio.

    Parameters:
        folder_path (str): The path to the folder containing TIFF files.

    Returns:
        list: A list of paths that can be read by rasterio.
    """
    path_list = []
    for file in glob.glob(tif_path+'/'+CONST.GET_TIF_STR):
        path_list.append(file)

    return path_list
