# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02utilities.ipynb.

# %% auto 0
__all__ = ['load_list_paths']

# %% ../nbs/02utilities.ipynb 3
import glob

from . import const_vals as CONST

# %% ../nbs/02utilities.ipynb 4
def load_list_paths(
    path : str , # path to the folder where all the tifs are located
    filter_file : bool , # when True, only file with suffix GET_FILE_STR will be listed
    
    )-> list :

    """
    Takes a folder path containing TIFF files and returns a list of paths
    that can be read by rasterio.

    Parameters:
        folder_path (str): The path to the folder containing TIFF files.

    Returns:
        list: A list of paths that can be read by rasterio.
    """
    path_list = []
    if filter_file:
        
        for file in glob.glob(path+'/'+CONST.GET_FILE_STR):
            path_list.append(file)
    else:
        for file in glob.glob(path+'/*'):
            path_list.append(file)


    return path_list
